# This is project specific rubocop configuration file.
# You can tweak project settings here
inherit_from:
  - ./.rubocop.localch.yml

Lint/IneffectiveAccessModifier:
  Enabled: false

Rails:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/NotToNo:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/Lambda:
  Enabled: false
